services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - ./misc:/docker-entrypoint-initdb.d

  app:
    depends_on:
      - database
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/fino_cars